version: '3'
services:
    mongodb:
      image: mongo:latest
      container_name: "mongodb"
      volumes:
        - ./database:/data
      ports:
        - 27017:27017
    courses-search:
      image: acn/courses-search
      ports:
        - "9090:9090"
      links:
        - mongodb
      environment:
        - "spring.profiles.active=dev"
      depends_on:
        - mongodb
    courses-registration:
      image: acn/courses-registration
      ports:
        - "8080:8080"
      links:
        - mongodb
      environment:
        - "spring.profiles.active=dev"
      depends_on:
        - mongodb
    courses-view:
      image: acn/courses-view
      ports:
        - "3000:3000"
      links:
        - courses-search
        - courses-registration
      environment:
        - "spring.profiles.active=dev"
      depends_on:
        - mongodb







